src/WebUI/Models/Contato.cs
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class Contato
    {
        public int Id { get; set; }

        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Display(Name = "Sobrenome")]
        public string Sobrenome { get; set; }

        [Display(Name = "E-mail")]
        public string Email { get; set; }
    }
}

src/WebUI/Models/ContatoViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class ContatoViewModel
    {
        public List<TelefoneViewModel> LstTelefoneViewModel { get; } = new List<TelefoneViewModel>();
        public int Id { get; set; }

        [Required(ErrorMessage = "Insira o Nome")]
        [MinLength(3, ErrorMessage = "O Nome deve ter pelo menos 3 caracteres")]
        [MaxLength(100, ErrorMessage = "O Nome deve ter no máximo 100 caracteres")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Insira o Sobrenome")]
        [MinLength(3, ErrorMessage = "O Sobrenome deve ter pelo menos 3 caracteres")]
        [MaxLength(100, ErrorMessage = "O Sobrenome deve ter no máximo 100 caracteres")]
        [Display(Name = "Sobrenome")]
        public string Sobrenome { get; set; }

        [Required(ErrorMessage = "Insira o E-mail")]
        [MinLength(10, ErrorMessage = "O E-mail deve ter pelo menos 3 caracteres")]
        [MaxLength(100, ErrorMessage = "O E-mail deve ter no máximo 100 caracteres")]
        [Display(Name = "E-mail")]
        public string Email { get; set; }
    }
}

src/WebUI/Controllers/ContatoController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using DAO;
using DTO;
using WebUI.Models;
using AutoMapper;
using System;


namespace WebUI.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoDAO _contatoDAO;
        private readonly IMapper _mapper;
        private readonly ITelefoneDAO _telefoneDAO;


        public ContatoController(IContatoDAO contatoDAO, IMapper mapper, ITelefoneDAO telefoneDAO)
        {
            _contatoDAO = contatoDAO;
            _mapper = mapper;
            _telefoneDAO = telefoneDAO;
        }

        public IActionResult Index()
        {
            var lstContatoDTO = _contatoDAO.Consultar();
            var lstContatoViewModel = new List<ContatoViewModel>();

            foreach (var contatoDTO in lstContatoDTO)
            {
                lstContatoViewModel.Add(_mapper.Map<ContatoViewModel>(contatoDTO));
            }

            return View(lstContatoViewModel);
        }

        public IActionResult Details(int id)
        {
            var contatoDTO = _contatoDAO.Consultar(id);

            var contatoViewModel = _mapper.Map<ContatoViewModel>(contatoDTO);

            var lstTelefoneDTO = _telefoneDAO.ConsultarPorContato(id);

            foreach (var telefoneDTO in lstTelefoneDTO)
            {
                contatoViewModel.LstTelefoneViewModel.Add(_mapper.Map<TelefoneViewModel>(telefoneDTO));
            }

            return View(contatoViewModel);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(ContatoViewModel contatoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var contatoDTO = _mapper.Map<ContatoDTO>(contatoViewModel);

            try
            {
                _contatoDAO.Criar(contatoDTO);
                TempData[Constants.Message.SUCCESS] = "Contato cadastrado com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var contatoDTO = _contatoDAO.Consultar(id);
            var contatoViewModel = _mapper.Map<ContatoViewModel>(contatoDTO);

            return View(contatoViewModel);
        }

        [HttpPost]
        public IActionResult Update(ContatoViewModel contatoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var contatoDTO = _mapper.Map<ContatoDTO>(contatoViewModel);

            try
            {
                _contatoDAO.Atualizar(contatoDTO);
                TempData[Constants.Message.SUCCESS] = "Contato atualizado com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            try
            {
                _contatoDAO.Excluir(id);
                TempData[Constants.Message.SUCCESS] = "Contato excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Index");
        }
    }
}

src/WebUI/Controllers/TelefoneController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using DAO;
using DTO;
using WebUI.Models;
using System;

namespace WebUI.Controllers
{
    public class TelefoneController : Controller
    {
        private readonly ITelefoneDAO _telefoneDAO;
        private readonly IMapper _mapper;
        public TelefoneController(ITelefoneDAO telefoneDAO, IMapper mapper)
        {
            _telefoneDAO = telefoneDAO;
            _mapper = mapper;
        }

        public IActionResult Create(int id)
        {
            var telefoneViewModel = new TelefoneViewModel() { ContatoId = id };

            return View(telefoneViewModel);
        }

        [HttpPost]
        public IActionResult Create(TelefoneViewModel telefoneViewModel)
        {
            var telefoneDTO = _mapper.Map<TelefoneDTO>(telefoneViewModel);

            try
            {
                _telefoneDAO.Criar(telefoneDTO);
                TempData[Constants.Message.SUCCESS] = "Telefone cadastrado com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Details", "Contato", new { id = telefoneViewModel.ContatoId });
        }

        public IActionResult Delete(int contatoId, int id)
        {
            try
            {
                _telefoneDAO.Excluir(id);
                TempData[Constants.Message.SUCCESS] = "Telefone excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Details", "Contato", new { id = contatoId });
        }

        public IActionResult Update(int id)
        {
            var telefoneDTO = _telefoneDAO.Consultar(id);

            var telefoneViewModel = _mapper.Map<TelefoneViewModel>(telefoneDTO);

            return View(telefoneViewModel);
        }

        [HttpPost]
        public IActionResult Update(TelefoneViewModel telefoneViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var telefoneDTO = _mapper.Map<TelefoneDTO>(telefoneViewModel);

            try
            {
                _telefoneDAO.Atualizar(telefoneDTO);
                TempData[Constants.Message.SUCCESS] = "Telefone atualizado com sucesso.";
            }
            catch (Exception ex)
            {
                TempData[Constants.Message.ERROR] = ex.Message;
            }

            return RedirectToAction("Details", "Contato", new { id = telefoneViewModel.ContatoId });
        }
    }
}

src/WebUI/Views/Contato/Create.cshtml
@model ContatoViewModel

@{
    ViewBag.Title = "Novo";
}

<h2>Criar Novo Contato</h2>

<form asp-controller="Contato" asp-action="Create">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Sobrenome" class="form-label"></label>
        <input asp-for="Sobrenome" class="form-control" />
        <span asp-validation-for="Sobrenome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <a asp-controller="Contato" asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>

</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WebUI/Views/Contato/Details.cshtml
@model ContatoViewModel

@{
    ViewBag.Title = "Detalhes";
}

@await Html.PartialAsync("_AlertMessagePartial")

<h2>Detalhes do contato</h2>

<form>

    <input asp-for="Id" hidden />
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label asp-for="Nome" class="form-label"></label>
                <input asp-for="Nome" class="form-control" disabled />
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                <label asp-for="Sobrenome" class="form-label"></label>
                <input asp-for="Sobrenome" class="form-control" disabled />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" disabled />
            </div>
        </div>
        <div class="col-lg-2">
            <a asp-controller="Telefone" asp-action="Create" asp-route-id="@Model.Id">Adicionar
                Telefone</a>
        </div>
        <div class="col-lg-2">
            <a asp-controller="Contato" asp-action="Index" asp-route-id="@Model.Id">Voltar</a>
        </div>
    </div>

</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.LstTelefoneViewModel[0].Numero)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LstTelefoneViewModel)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    <a asp-controller="Telefone" asp-action="Update" asp-route-id="@item.Id">Atualizar</a>
                    <a asp-controller="Telefone" asp-action="Delete" asp-route-contatoId="@Model.Id" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/WebUI/Views/Contato/Index.cshtml
@model IEnumerable<ContatoViewModel>

@{
    ViewBag.Title = "Todos";
}

@await Html.PartialAsync("_AlertMessagePartial")

<h1>Contatos</h1>

<a asp-controller="Contato" asp-action="Create" class="btn btn-primary">Novo</a>

<table class="table table-responsive-lg">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(item => item.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(itemModel => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(itemModel => item.Sobrenome)
                </td>
                <td>
                    @Html.DisplayFor(itemModel => item.Email)
                </td>
                <td>
                    <a asp-controller="Contato" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary">Detalhes</a>
                    <a asp-controller="Contato" asp-action="Update" asp-route-id="@item.Id" class="btn btn-outline-warning">Atualizar</a>
                    <a asp-controller="Contato" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/WebUI/Views/Contato/Update.cshtml
@model ContatoViewModel

@{
    ViewBag.Title = "Atualizar";
}

<form asp-action="Update">

    <div asp-validation-summary="All" class="text-danger"></div>

    <input asp-for="Id" hidden />

    <div class="form-group">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Sobrenome" class="form-label"></label>
        <input asp-for="Sobrenome" class="form-control" />
        <span asp-validation-for="Sobrenome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>

</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}